name 'doare-base'
maintainer 'Doare, Inc'
maintainer_email 'devs@doare.org'
license 'Proprietary - All Rights Reserved'
description 'Installs/Configures doare-base'
long_description 'Installs/Configures doare-base'
version '0.1.4'

depends          'apt'
depends          'build-essential', '~> 2.2.4'
depends          'locale', '~> 1.0.2'
depends          'user', '~> 0.4.2'
